- name: Update and add dependencies
  ansible.builtin.apt:
    update_cache: true
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - gnupg
      - software-properties-common
  become: true

- name: Add HashiCorp GPG key
  ansible.builtin.apt_key:
    url: "https://apt.releases.hashicorp.com/gpg"
    state: present
    validate_certs: true
    keyring: "/usr/share/keyrings/hashicorp-archive-keyring.gpg"
  become: true

- name: Add HashiCorp repository to apt
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main"
    state: present
    filename: "hashicorp"
  become: true

- name: Install Terraform
  ansible.builtin.apt:
    name: terraform
    state: latest
  become: true
